# Generated by Django 4.0.4 on 2022-04-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_profile_passing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
