# Generated by Django 4.0.4 on 2022-04-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_profile_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
